/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jaky_mupdf_core_MuPDFCore_Cookie */

#ifndef _Included_com_jaky_mupdf_core_MuPDFCore_Cookie
#define _Included_com_jaky_mupdf_core_MuPDFCore_Cookie
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
