/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jaky_mupdf_core_MuPDFCore */

#ifndef _Included_com_jaky_mupdf_core_MuPDFCore
#define _Included_com_jaky_mupdf_core_MuPDFCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    gprfSupportedInternal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jaky_mupdf_core_MuPDFCore_gprfSupportedInternal
  (JNIEnv *);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    openFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_jaky_mupdf_core_MuPDFCore_openFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    openBuffer
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_jaky_mupdf_core_MuPDFCore_openBuffer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    fileFormatInternal
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jaky_mupdf_core_MuPDFCore_fileFormatInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    isUnencryptedPDFInternal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jaky_mupdf_core_MuPDFCore_isUnencryptedPDFInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    countPagesInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jaky_mupdf_core_MuPDFCore_countPagesInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    gotoPageInternal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_gotoPageInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getPageWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getPageWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getPageHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getPageHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    drawPage
 * Signature: (Landroid/graphics/Bitmap;IIIIIIJ)V
 */
JNIEXPORT jboolean JNICALL Java_com_jaky_mupdf_core_MuPDFCore_drawPage
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    updatePageInternal
 * Signature: (Landroid/graphics/Bitmap;IIIIIIIJ)V
 */
JNIEXPORT jboolean JNICALL Java_com_jaky_mupdf_core_MuPDFCore_updatePageInternal
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    searchPage
 * Signature: (Ljava/lang/String;)[Landroid/graphics/RectF;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jaky_mupdf_core_MuPDFCore_searchPage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    text
 * Signature: ()[[[[Lcom/jaky/mupdf/data/TextChar;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jaky_mupdf_core_MuPDFCore_text
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    textAsHtml
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jaky_mupdf_core_MuPDFCore_textAsHtml
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    addMarkupAnnotationInternal
 * Signature: ([Landroid/graphics/PointF;I)V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_addMarkupAnnotationInternal
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    addInkAnnotationInternal
 * Signature: ([[Landroid/graphics/PointF;)V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_addInkAnnotationInternal
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    deleteAnnotationInternal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_deleteAnnotationInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    passClickEventInternal
 * Signature: (IFF)I
 */
JNIEXPORT jint JNICALL Java_com_jaky_mupdf_core_MuPDFCore_passClickEventInternal
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    setFocusedWidgetChoiceSelectedInternal
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_setFocusedWidgetChoiceSelectedInternal
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getFocusedWidgetChoiceSelected
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getFocusedWidgetChoiceSelected
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getFocusedWidgetChoiceOptions
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getFocusedWidgetChoiceOptions
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getFocusedWidgetSignatureState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getFocusedWidgetSignatureState
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    checkFocusedSignatureInternal
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jaky_mupdf_core_MuPDFCore_checkFocusedSignatureInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    signFocusedSignatureInternal
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jaky_mupdf_core_MuPDFCore_signFocusedSignatureInternal
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    setFocusedWidgetTextInternal
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jaky_mupdf_core_MuPDFCore_setFocusedWidgetTextInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getFocusedWidgetTextInternal
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getFocusedWidgetTextInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getFocusedWidgetTypeInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getFocusedWidgetTypeInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getPageLinksInternal
 * Signature: (I)[Lcom/jaky/mupdf/data/LinkInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getPageLinksInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getWidgetAreasInternal
 * Signature: (I)[Landroid/graphics/RectF;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getWidgetAreasInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getAnnotationsInternal
 * Signature: (I)[Lcom/jaky/mupdf/data/Annotation;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getAnnotationsInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getOutlineInternal
 * Signature: ()[Lcom/jaky/mupdf/data/OutlineItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getOutlineInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    hasOutlineInternal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jaky_mupdf_core_MuPDFCore_hasOutlineInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    needsPasswordInternal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jaky_mupdf_core_MuPDFCore_needsPasswordInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    authenticatePasswordInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jaky_mupdf_core_MuPDFCore_authenticatePasswordInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    waitForAlertInternal
 * Signature: ()Lcom/jaky/mupdf/data/MuPDFAlertInternal;
 */
JNIEXPORT jobject JNICALL Java_com_jaky_mupdf_core_MuPDFCore_waitForAlertInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    replyToAlertInternal
 * Signature: (Lcom/jaky/mupdf/data/MuPDFAlertInternal;)V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_replyToAlertInternal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    startAlertsInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_startAlertsInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    stopAlertsInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_stopAlertsInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    destroying
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_destroying
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    hasChangesInternal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jaky_mupdf_core_MuPDFCore_hasChangesInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    saveInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_saveInternal
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    createCookie
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jaky_mupdf_core_MuPDFCore_createCookie
  (JNIEnv *, jobject);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    destroyCookie
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_destroyCookie
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    abortCookie
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_abortCookie
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    startProofInternal
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jaky_mupdf_core_MuPDFCore_startProofInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    endProofInternal
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_endProofInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getNumSepsOnPageInternal
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getNumSepsOnPageInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    controlSepOnPageInternal
 * Signature: (IIZ)I
 */
JNIEXPORT void JNICALL Java_com_jaky_mupdf_core_MuPDFCore_controlSepOnPageInternal
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    getSepInternal
 * Signature: (II)Lcom/jaky/mupdf/data/Separation;
 */
JNIEXPORT jobject JNICALL Java_com_jaky_mupdf_core_MuPDFCore_getSepInternal
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jaky_mupdf_core_MuPDFCore
 * Method:    javascriptSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jaky_mupdf_core_MuPDFCore_javascriptSupported
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
